### PR TITLE
support --build-type argument for debug/release build

### PR DESCRIPTION
**Pull request by xandox**
It works, but not entirely as expected.
Maintaining both debug and release builds simultaneously does not work. I believe this is because `scikit-build` uses the same build directory for both debug and release builds.

### CODE REVIEW

**Comment by d-krupke** [comment]
Hey Ilya,

Thanks for your contribution. This looks like a useful addition!
I will take a closer look the next few days; I am unfortunately totally swamped with other stuff at the moment.

Best,
Dominik

**Comment by d-krupke** [comment]
Not forgotten: Will take care of it next week during the Christmas break :)

**Comment by d-krupke** [comment]
Merged and the CI seems to work after removing Python 3.7. Unfortunately, I noticed that skbuild-conan is not ready for Python 3.13, yet. Already opened an issue. Hopefully, easy to fix.

Thanks again for contributing.

**Comment by xandox** [comment]
>Thanks again for contributing.

It's my pleasure.

But I didn't get that part with python versions, how it related to the PR? I hope I did not use some new Python language feature which not was used yet.

**Comment by d-krupke** [comment]
Only relates indirectly: The CI was still set up for Python 3.7 but it is no longer supported by GitHub, making the CI fail for the merged version. I just pushed the CI to test on Python 3.8 and 3.12 instead.

**Comment by xandox** [comment]
Oh, ok. Thank you for accepting!

**Pull request merged**
